server:
  port: 8080

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
